import json
from typing import Optional, Any, Dict
from groq import AsyncGroq, GroqError
from app.config.settings import settings
from app.core.logging import logger
from app.core.exceptions import LLMException
from app.core.retry import async_retry

class LLMClient:
    def __init__(self):
        self.api_key = settings.GROQ_API_KEY
        self.model = settings.DEFAULT_MODEL
        self.temperature = settings.TEMPERATURE
        
        self.is_mock = self.api_key == "mock_groq_api_key" or not self.api_key
        
        if not self.is_mock:
            self.client = AsyncGroq(api_key=self.api_key)
        else:
            logger.warning("GROQ_API_KEY is not configured or is set to mock. Running LLM Client in MOCK mode.")
            self.client = None

    @async_retry(retries=3, delay=1.0, backoff=2.0, exceptions=(GroqError, Exception))
    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: Optional[Dict[str, Any]] = None,
        model_role: Optional[str] = None
    ) -> str:
        """
        Generates completions from Groq LLM. Retries with exponential backoff on connection/rate errors.
        Falls back to deterministic mocks if API key is not configured.
        """
        if self.is_mock:
            return self._get_mock_response(system_prompt, user_prompt)
        
        try:
            chosen_model = self.model
            if model_role == "planner":
                chosen_model = settings.PLANNER_MODEL
            elif model_role == "generator":
                chosen_model = settings.GENERATOR_MODEL
            elif model_role == "reflection":
                chosen_model = settings.REFLECTION_MODEL
                
            logger.info(f"Calling Groq LLM API (Role: {model_role}, Model: {chosen_model}, Response Format: {response_format})")
            
            # Formulate call args
            kwargs = {
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "model": chosen_model,
                "temperature": self.temperature,
            }
            if response_format:
                kwargs["response_format"] = response_format
                
            response = await self.client.chat.completions.create(**kwargs)
            return response.choices[0].message.content
        except GroqError as ge:
            logger.error(f"Groq API Error: {ge}")
            raise LLMException(f"Groq LLM call failed: {str(ge)}")
        except Exception as e:
            logger.error(f"Unexpected error during Groq execution: {e}")
            raise LLMException(f"LLM generation failed: {str(e)}")

    def _get_mock_response(self, system_prompt: str, user_prompt: str) -> str:
        """Simulates structured JSON outputs for offline usage/testing."""
        logger.info("Generating mock LLM response...")
        user_prompt_lower = user_prompt.lower()
        system_prompt_lower = system_prompt.lower()
        
        # Determine prompt type
        if "content generator" in system_prompt_lower:
            # Content Generator response
            return json.dumps({
                "title": "Enterprise Strategic Document",
                "metadata": {
                    "author": "Autonomous AI Agent",
                    "version": "1.0"
                },
                "sections": [
                    {
                        "heading": "1. Executive Summary",
                        "subheading": "1.1 Scope and Objectives",
                        "paragraphs": [
                            "This document represents the consolidated findings and strategic recommendations generated by the Enterprise Agent.",
                            "The methodology incorporates context gathered from local enterprise repositories and real-time public market intelligence."
                        ],
                        "bullets": [
                            "Establish scalable architecture mapping business goals to microservices.",
                            "Leverage sentence embeddings for vector retrieval.",
                            "Maintain rigorous reflection quality loops."
                        ],
                        "tables": [
                            {
                                "headers": ["Metric", "Baseline", "Target"],
                                "rows": [
                                    ["Retrieval Latency", "1.2s", "< 200ms"],
                                    ["Generation Accuracy", "82%", "> 95%"],
                                    ["User Satisfaction", "4.0 / 5.0", "> 4.7 / 5.0"]
                                ]
                            }
                        ],
                        "references": ["IEEE Agent Architectures", "Groq Speed Benchmarks 2026"]
                    },
                    {
                        "heading": "2. Framework Analysis",
                        "subheading": "2.1 Technical Evaluation",
                        "paragraphs": [
                            "Modern cloud architectures rely on low coupling and high cohesion to facilitate rapid iteration.",
                            "Integrating self-reflection checkpoints minimizes hallucinated sections and duplicate headings."
                        ],
                        "bullets": [
                            "FastAPI handles async endpoint routing",
                            "python-docx structures word document rendering"
                        ],
                        "tables": [],
                        "references": []
                    }
                ]
            })
            
        elif "quality control" in system_prompt_lower or "reflection" in system_prompt_lower:
            # Reflection response
            return json.dumps({
                "passed": True,
                "score": 9.0,
                "completeness": "The generated document contains all required segments including Introduction, Analysis, and References.",
                "grammar": "Spelling and grammar are correct. Sentence structure is clear and professional.",
                "consistency": "Formatting, hierarchy, and naming conventions are consistent.",
                "suggestions": []
            })
            
        else:
            # Planner response
            intent = "Proposal"
            if "technical design" in user_prompt_lower or "architecture" in user_prompt_lower:
                intent = "Technical Design"
            elif "minutes" in user_prompt_lower:
                intent = "Meeting Minutes"
            elif "sop" in user_prompt_lower:
                intent = "SOP"
            
            return json.dumps({
                "goal": f"Create a professional {intent} based on: {user_prompt[:60]}...",
                "intent": intent,
                "assumptions": [
                    "Target audience values clarity and professional layout",
                    "Standards from the RAG knowledge base should take precedence",
                    "Web search is needed for current framework details"
                ],
                "execution_plan": [
                    {
                        "step": 1,
                        "tool": "rag_tool",
                        "inputs": {"query": f"{intent} structure and guidelines"},
                        "reason": "Retrieve template and guidelines from enterprise knowledge base"
                    },
                    {
                        "step": 2,
                        "tool": "search_tool",
                        "inputs": {"query": f"latest industry standards for {intent}"},
                        "reason": "Ensure content reflects the most up-to-date best practices"
                    }
                ],
                "required_tools": ["rag_tool", "search_tool"],
                "validation_checklist": [
                    "Verify document contains Title and Date",
                    "Confirm inclusion of all requested sections",
                    "Check for professional, corporate tone"
                ],
                "expected_output": "Structured sections containing Executive Summary, Core Content, and References."
            })

llm_client = LLMClient()
